source("inst/enclave/dependency-release-review-v1/prepare.R")
n <- 0L
ok <- function(x) {stopifnot(isTRUE(x));n<<-n+1L}
fails <- function(x) inherits(tryCatch({force(x);NULL},error=identity),"error")
spec <- list(kind="conditional_counts_internal",target="gender",parents=list("age_band",character()),
  tables=list(data.frame(age_band=c("a","a","b","b"),gender=c("f","m","f","m"),count=c(3,97,12,28)),
    data.frame(gender=c("f","m"),count=c(15,125))))
p <- ds_protect_table(spec)
ok(all(is.na(p$table$count[1:2])))
ok(identical(p$table$count[3:4],c(10,30)))
ok(!"tables" %in% names(p))
ok(identical(spec$tables[[1]]$count,c(3,97,12,28)))
b <- spec;b$tables[[1]]$count[1]<- -1;ok(fails(ds_protect_table(b)))
b <- spec;b$tables[[1]]$count[1]<- NA;ok(fails(ds_protect_table(b)))
b <- spec;b$tables[[1]]<-rbind(b$tables[[1]],b$tables[[1]][1,]);ok(fails(ds_protect_table(b)))
model <- list(kind="ridge_logistic_v1",levels=list(age_band=c("a","b")),
  coefficients=c(`(Intercept)`=-2,`age_band=b`=.1),lambda=.01)
attr(model$coefficients,"fit_diagnostics")<-list(secret="MUST_NOT_COPY")
stripped <- ds_model(list(model=model))
ok(is.null(attr(stripped$coefficients,"fit_diagnostics")))
b<-model;b$coefficients[1]<-Inf;ok(fails(ds_model(list(model=b))))
rounds<-c(sprintf("react1.r%02d",1:19),sprintf("react2.r%02d",1:6))
z<-list(status="fitted_pending_review",fit=list(model=model,validation="MUST_NOT_COPY"),
  conditional_tables=list(gender=spec),symptom_tables=list(),ct_tables=list(),vaccine=list(conflicts="MUST_NOT_COPY"))
sym<-list(kind="conditional_counts_internal",target="symptom",parents=list("outcome",character()),
  tables=list(data.frame(outcome=c("positive","positive"),symptom=c("selected","not_selected"),count=c(22,13))))
z$symptom_tables<-list(occ_abcdef=sym)
ct<-sym;ct$target<-"ct_state";names(ct$tables[[1]])[2]<-"ct_state";ct$tables[[1]]$ct_state<-c("zero","over0_to10")
z$ct_tables<-list(CT_VALUE1=ct)
models<-setNames(lapply(rounds,function(r){a<-z;a$round_id<-r;a}),rounds)
d<-tempfile();dir.create(d);source_file<-file.path(d,"parameters-AND-COUNTS-NOT-APPROVED.rds");saveRDS(models,source_file)
hash<-ds_hash(source_file);out<-file.path(d,"selected")
react_prepare_dependency_release_review(d,out)
ok(identical(hash,ds_hash(source_file)))
payload<-readRDS(file.path(out,"SELECTION-NOT-APPROVED.rds"))
ok(length(payload$rounds)==25)
ok(identical(payload$rounds[[1]]$ct_counts$CT_VALUE1$table$count,c(20,15)))
ok(identical(payload$rounds[[1]]$symptom_counts$occ_abcdef$table$count,c(20,15)))
ok(!any(grepl("MUST_NOT_COPY",unlist(payload),fixed=TRUE)))
ok(identical(payload$status,"INTERNAL_PENDING_DISCLOSURE_REVIEW"))
dec<-read.csv(file.path(out,"REVIEW_DECISIONS.csv"));ok(all(dec$decision=="pending"))
ok(fails(react_prepare_dependency_release_review(d,out)))
models[[1]]$status<-"refit_failed";saveRDS(models,source_file)
ok(fails(react_prepare_dependency_release_review(d,file.path(d,"bad"))))
ok(!dir.exists(file.path(d,"bad")))
cat(n,"synthetic-only checks passed\n")
